### ISSUE TITLE
Improve style of info icons and hover-over text

### ISSUE THREAD

**Issue by tkuhn** [knowledgepixels/nanodash#112]
Like this: 
![image](https://github.com/knowledgepixels/nanodash/assets/684096/4dd5d212-949d-41d3-949a-c76fd143e83e)

**Comment by phvonessen** [comment]
low hanging: change color of i-symbol to blue

**Comment by tkuhn** [comment]
i-symbol is improved and blue with 85275aecd86ee7044c9595282772fdd77640f26e, but info box needs a bit more work.

**Comment by tkuhn** [comment]
Done with 1d878d218ac6219a2ded33823ff4ee8028788219.
