### ISSUE TITLE
Move "Switch to Reviewer View" to right-hand-side column

### ISSUE THREAD

**Issue by tkuhn** [knowledgepixels/nanodash#118]
Move "Switch to Reviewer View" to right-hand-side column (below "Author Instruction" in connector pages.

**Comment by phvonessen** [comment]
Update text: To assess this nanopublication, check its content below, most importantly the blue assertion part, -> yellow

**Comment by tkuhn** [comment]
Done with bd08046330fa9a2bfddb424d1b080786ff57913d.
