### ISSUE TITLE
Harmonize input field height and text alignment

### ISSUE THREAD

**Issue by phvonessen** [knowledgepixels/nanodash#129]
<img width="919" alt="Bildschirmfoto 2024-05-14 um 11 40 06" src="https://github.com/knowledgepixels/nanodash/assets/129521658/8fc85048-f643-40c2-9208-3ea684b95b62">

**Comment by tkuhn** [comment]
Done with 1c8668116756cd14f6e8464fd9029a91bb5ae95a.

![image](https://github.com/knowledgepixels/nanodash/assets/684096/d6f1a500-7601-4781-acd3-eaecf7ea5728)
