### ISSUE TITLE
Next suggestion for progressbar

### ISSUE THREAD

**Issue by phvonessen** [knowledgepixels/nanodash#130]
<img width="886" alt="grafik" src="https://github.com/knowledgepixels/nanodash/assets/129521658/7068def2-4a8c-4bb6-a920-d6f98af496aa">

left and right aligned

**Comment by tkuhn** [comment]
OK, I managed to have a full-width progress bar only with CSS changes (7d60853efcf7b426fce65d4a3fce35313c6a6904):

![image](https://github.com/knowledgepixels/nanodash/assets/684096/7e28c324-b829-4ca7-83a0-861f7bd0761a)
